export { default as AuthenticationPage } from './auth/AuthenticationPage'
export { default as AccountPage } from './account/AccountPage'
export { default as AccountStatPage } from './account/AccountStatPage'
export { default as CourseWatchPage } from './course/CourseWatchPage'
export { default as AdminCoursePage } from './admin/AdminCoursePage'
export { default as LoginSuccessPage } from './auth/LoginSuccessPage'
export { default as AdminLoginPage } from './auth/AdminLoginPage'
export { default as AdminSignUpPage } from './auth/AdminSignUpPage'
